### ISSUE TITLE
Provide a way to continue failed Multipart Uploads

### ISSUE THREAD

**Issue by ochaton** [peak/s5cmd#566] opened 2023-05-10 08:59 UTC
# Subject
s5cmd is truly great cli to deal with S3-compatible storages.

But during upload of massive blobs (500GB+) s5cmd aborts multipart upload when UploadPart request fails subsequently many times. This behaviour cancels progress of long running upload (3-4 hours) and does not provide a way to continue from last successfully uploaded part.

Maybe, you can add flag `--continue` or something like that where user may pass `uploadId` of multipart upload they want to resume?

Error message could return unfinished `uploadId` and description to user how to resume failed upload

**Comment by igungor** [comment] 2023-07-28 13:35
Duplicate of #528

**Closed by igungor** 2023-07-28 13:35 UTC
