### ISSUE TITLE
feat: add source-endpoint-url and dest-endpoint-url as separate parameters

### ISSUE THREAD

**Issue by dmbyte** [peak/s5cmd#672] opened 2023-10-04 17:30 UTC
There are times where it is necessary to copy between 2 S3 compatible storage devices that require the use of the endpoint-url parameter. Adding distinct source-endpoint-url and destination-endpoint-urls significantly widens potential use-cases.

**Comment by seruman** [comment] 2023-10-08 19:11
Hi @dmbyte 
I do not think accepting separate endpoint URLs would not help as  s5cmd does not support copy on cross cloud environments right now. You may use your disk as pointed here; https://github.com/peak/s5cmd/issues/595#issuecomment-1655675032 ; as a a temporary stage between them.

Duplicate of #529.

**Closed by seruman** 2023-10-08 19:11 UTC
