### ISSUE TITLE
Error parsing regexp: invalid UTF-8

### ISSUE THREAD

**Issue by shinsenter** [peak/s5cmd#332] opened 2021-07-30 07:58 UTC
I got an error:
```
ERROR "cp /home/www/catalogue/18948/ s3://production/catalogue/18948/": error parsing regexp: invalid UTF-8: `Ｇ\.jpg.*$`
```
when ran this command:
```
docker run --rm -it \
-v /root/.aws:/root/.aws \
-v /home/webike/www:/home/webike/www \
peakcom/s5cmd \
--endpoint-url=https://my-endpoint \
cp --acl public-read --if-source-newer --if-size-differ \
/home/www/catalogue/18948/ s3://production/catalogue/18948/
```

Please help.

**Comment by igungor** [comment] 2023-07-28 09:28
I couldn't reproduce the problem you're having. The problematic filename is in the error you pasted: `Ｇ.jpg`. **G** is not the ASCII `G`, but it's `Ｇ`.

I tried to create this file and upload to S3, and it works for s5cmd `v2.1.0`.

```
unicode-regex  Δ ls
Ｇ.jpg
unicode-regex  Δ s5cmd cp . s3://bucket/ibrahim/unicode-test/
cp Ｇ.jpg s3://bucket/ibrahim/unicode-test/Ｇ.jpg
unicode-regex  Δ 
```

Do you still see this problem with latest s5cmd build? If so, could you share a reproducer so we can debug the problem properly. I'm closing the issue but please re-open when you share more details about the problem.

**Closed by igungor** 2023-07-28 09:28 UTC

**Comment by woniuzhang** [comment] 2023-08-17 01:06
Hi, I had the same error.   My s5cmd version is  v2.1.0-3efbbe8.

**Comment by igungor** [comment] 2023-08-18 06:26
@woniuzhang Could you share the command you executed please? We'll take a look.

**Comment by woniuzhang** [comment] 2023-08-18 06:32
> @woniuzhang Could you share the command you executed please? We'll take a look.

s5cmd --endpoint-url=https://us-1.cdn77-storage.com sync --exclude "*.php"

 error parsing regexp: invalid UTF-8: `������
