### ISSUE TITLE
Does not support Cloudflare R2 multi part uploads

### ISSUE THREAD

**Issue by Lusitaniae** [peak/s5cmd#525] opened 2022-10-19 11:16 UTC
Similar to https://github.com/s3tools/s3cmd/issues/1273 

Cloudflare is returning a different ETAG value and breaking the S3 

```
./s5cmd version
v2.0.0-83ce8bc
```

```
$ ./s5cmd --credentials-file=/etc/s5cmd-r2.cfg --endpoint-url https://[endpoint].r2.cloudflarestorage.com cp test.tar s3://[bucket-name]
ERROR "cp test.tar.zst s3://[bucket-name]/test.tar": MultipartUpload: upload multipart failed upload id: APWqZzKqCR72sxCp2YBxWv4Ws4+6j8dqrntAIyj5E6tHhrLX6QyjPmRz1vHA+xqCxaQD/fA8mjiYebA49C8ourPxGZs+KAPNIqTBqmSCFfBE3ZcEpWVL/PM1ayCfWaBEhRnNY8mJzb+p6keD5QoZO9HvzHAe8M0fPlUg7Gy9g4g2BEcyb2FUBD5fqEkV6r8zbTAtYGRvqE9IqvyDWnUdrFyuT7+BoX+vCpPewty7Utruzs8pS2YD5XIuuUeb4VtnF/ksL7eEuP/ISW275iV4NuBjIS0uimORr25Il+uI0lI2NhVgZJPxHhVGLiwp+fRe1w== caused by: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your secret access key and signing method.  status code: 403, request id: , host id:

```

(don't mind the error message, `ls` and simple uploads work fine)

**Comment by Frederik-Baetens** [comment] 2022-11-19 06:47
This may not be the same issue as in s3cmd, since as far as I know, S5cmd doesn't perform the same md5 check, which is what breaks the compatibility between s3cmd and R2.

Also it seems like if I choose a new filename every time I can get the multipart upload to succeed. keeping the concurrency to lower than 50 also seems to help, but i'm not sure that's relevant. Once an upload to a filename failed with this error, it seems to fail on every subsequent run that attempts to overwrite that file. Choosing a new filename works.

**Comment by Frederik-Baetens** [comment] 2022-11-19 07:27
From some more testing: keeping the concurrency below 50 generally seems to work. Was able to saturate a 25Gbit connection when testing R2 with this tool.

**Comment by Frederik-Baetens** [comment] 2022-11-22 09:54
Hmm, I I've also been able to get these SignatureDoesNotMatch errors in RClone, so this might actually be an incompatibility between the aws-sdk-go and R2.

**Comment by Frederik-Baetens** [comment] 2022-11-30 17:47
I found this RClone issue, which has now been solved. Might s5cmd suffer from a similar issue? https://github.com/rclone/rclone/issues/5422

**Comment by salim-b** [comment] 2023-12-11 03:01
I think this issue has been fixed by Cloudflare [on June 21, 2023](https://developers.cloudflare.com/r2/reference/changelog/#2023-06-21). The corresponding [documentation](https://developers.cloudflare.com/r2/objects/multipart-objects/#etags) now says:

> The ETags for objects uploaded via multipart are different than those uploaded with PutObject.
>
> For uploads created after June 21, 2023, R2’s multipart ETags now mimic the behavior of S3. The ETag of each individual part is the MD5 hash of the contents of the part. The ETag of the completed multipart object is the hash of the MD5 sums of each of the constituent parts concatenated together followed by a hyphen and the number of parts uploaded.

**Comment by leng-yue** [comment] 2024-06-10 06:33
The issue is still there

**Comment by igungor** [comment] 2024-08-27 06:47
@bercknash Thanks for chiming in!

I've verified that it works as expected:

```bash
# s5cmd --profile r2 --endpoint-url https://<account-id>.r2.cloudflarestorage.com cp 10mb.file s3://<bucket>/
cp 10mb.file s3://<bucket>/10mb.file

$ echo $?
0
```

**Closed by igungor** 2024-08-27 06:47 UTC
