### ISSUE TITLE
Retain Modified date on copy from S3 to local

### ISSUE THREAD

**Issue by Krobar** [peak/s5cmd#161] opened 2020-04-20 12:43 UTC
Is this possible? 

The reason I ask is for this scenario:
s5cmd cp s3://bucket/* /tmp/
Change some of the files in /tmp but not all
s5cmd cp -n -u /tmp/ s3://bucket/

**Comment by igungor** [comment] 2020-04-21 15:10
Currently, it's not possible. Instead of storing modification time of objects, it's best to use hash of the content to compare modifications.

Duplicate of #152

**Closed by igungor** 2020-04-21 15:10 UTC
