### ISSUE TITLE
Sync --delete not working 

### ISSUE THREAD

**Issue by gabronick** [peak/s5cmd#382] opened 2021-11-26 05:53 UTC
Sync works perfect but when using "sync --delete" does not delete the files from S3

example:

  s5cmd sync --delete / external / s3: //bucket
  
  the 1.txt file that no longer exists in /extenal/1.txt (it was before+synced), is not removed from the bucket now

**Comment by igungor** [comment] 2022-02-18 08:02
I can't reproduce. Could you please prepare a reproducer case for us so that we can debug what's causing this behaviour?

**Comment by igungor** [comment] 2022-04-06 10:47
I'm closing the issue. Please re-open if you can provide us a reproducer.

**Closed by igungor** 2022-04-06 10:47 UTC
