### ISSUE TITLE
Feature request: Add min-age/max-age to identify the objects

### ISSUE THREAD

**Issue by rsomu** [peak/s5cmd#501] opened 2022-08-25 22:22 UTC
It would be nice if we can filter the objects in s5cmd by min-age or max-age (similar to what rclone offers).
This will help with massive data migration between S3 buckets where having the flexibility to select objects by date/time is very useful.

For example, the following command will list all objects from the object store upto 9 days old.

rclone --max-age 9d lsl west:test-bucket

**Comment by igungor** [comment] 2023-07-28 13:13
Duplicate of #388

**Closed by igungor** 2023-07-28 13:13 UTC
Labels: feature-request
