### ISSUE TITLE
Installation on OSX using Homebrew

### ISSUE THREAD

**Issue by neer201** [peak/s5cmd#415] opened 2022-03-23 08:30 UTC
Hi there! I try to install s5cmd tool using Homebrew. But it doesn't work.

```
➜  ~ brew tap peak/s5cmd https://github.com/peak/s5cmd

==> Tapping peak/s5cmd
Cloning into '/usr/local/Homebrew/Library/Taps/peak/homebrew-s5cmd'...
remote: Enumerating objects: 10403, done.
remote: Counting objects: 100% (1528/1528), done.
remote: Compressing objects: 100% (779/779), done.
remote: Total 10403 (delta 959), reused 1120 (delta 723), pack-reused 8875
Receiving objects: 100% (10403/10403), 21.66 MiB | 2.03 MiB/s, done.
Resolving deltas: 100% (4816/4816), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/peak/homebrew-s5cmd/Formula/s5cmd.rb
s5cmd: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the peak/s5cmd tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/peak/homebrew-s5cmd/Formula/s5cmd.rb:9

Error: Cannot tap peak/s5cmd: invalid syntax in tap!
```

Is there some solution for homebrew installation?

**Comment by igungor** [comment] 2022-03-23 10:36
Duplicate of #374

**Closed by igungor** 2022-03-23 10:36 UTC
