### ISSUE TITLE
Support endpoint_url in aws config 

### ISSUE THREAD

**Issue by zalsader** [peak/s5cmd#760] opened 2024-09-30 02:41 UTC
The new aws client (v2) supports adding the [endpoint url in the config](https://docs.aws.amazon.com/cli/v1/userguide/cli-configure-files.html#cli-config-endpoint_url), for example:
```ini
[default]
endpoint_url=http://example.com
```

Is it possible to add support for this here?

I dug a bit into it, and parsing the config file is done by https://github.com/aws/aws-sdk-go, while the new client uses https://github.com/aws/aws-sdk-go-v2

I think we could read the ini for that specific value if switching to the new sdk is not planned.

**Comment by rasca** [comment] 2024-10-03 12:58
Duplicate of #694

**Comment by zalsader** [comment] 2024-10-03 17:20
Thank you, somehow it didn't turn up when I searched.

**Closed** 2024-10-03 17:20 UTC
