### ISSUE TITLE
Upload multiple files to S3 bucket fails

### ISSUE THREAD

**Issue by bounlu** [peak/s5cmd#635] opened 2023-08-04 09:06 UTC
I want to upload multiple local files matching a pattern to an S3 bucket, as given in the example:

```
$ s5cmd cp --help
  
Examples:
  06. Upload matching files to S3 bucket
     > s5cmd cp dir/*.gz s3://bucket/
```

However, I get the below error:

```
$ s5cmd --dry-run cp /data/*.bam s3://data/
ERROR "cp /data/a.deduplicated.sorted.bam /data/b.deduplicated.sorted.bam /data/c.deduplicated.sorted.bam /data/d.deduplicated.sorted.bam /data/e.deduplicated.sorted.bam s3://data/": expected source and destination arguments
```

**Comment by seruman** [comment] 2023-08-04 09:26
Your shell's glob expansion kicks in and causes multiple files to be passed to the `cp` command which does not support variadic arguments.

Examples are updated in master branch with https://github.com/peak/s5cmd/pull/581 but it's yet to release. Can you try with quoting `/data/*.bam` according to your shell?

```zsh
; s5cmd cp doc/* s3://some-bucket/selman/wildcardtest/
ERROR "cp doc/benchmark1.png doc/benchmark2.png doc/benchmark3.png doc/s5cmd_header.jpg doc/usage.png s3://some-bucket/selman/wildcardtest/": expected source and destination arguments

; s5cmd cp 'doc/*' s3://some-bucket/selman/wildcardtest/
cp doc/benchmark1.png s3://some-bucket/selman/wildcardtest/benchmark1.png
cp doc/benchmark3.png s3://some-bucket/selman/wildcardtest/benchmark3.png
cp doc/benchmark2.png s3://some-bucket/selman/wildcardtest/benchmark2.png
cp doc/s5cmd_header.jpg s3://some-bucket/selman/wildcardtest/s5cmd_header.jpg
cp doc/usage.png s3://some-bucket/selman/wildcardtest/usage.png
```

Closing as duplicate of https://github.com/peak/s5cmd/issues/555

**Closed by seruman** 2023-08-04 09:26 UTC
